# Generated by Django 5.0 on 2024-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookShop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
